### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by Jazmin7** [Barbany/Multi-speaker-Neural-Vocoder#5]
Hi，
I encountered an error.

/anaconda3/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 44, in reset_parameters
    stdv = 1. / math.sqrt(n)
ZeroDivisionError: float division by zero

Can you tell me why it is happened?
Thank you!

**Comment by Barbany** [comment]
I don't see the whole error message here and would be much more helpful. Nevertheless it seems that your data is not properly loaded. Have you noted that the dataset is not in the repo but only the structure that you have to follow?
